import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import useSWR from "swr";

const inter = Inter({ subsets: ["latin"] });

const fetcher = (args: any) => fetch(args).then((res) => res.json());

export default function Home() {
  const { data, error, isLoading } = useSWR(
    "https://danielcodex.com/wp-json/wp/v2/posts",
    fetcher
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {(() => {
          if (error) return <h1>failed to load</h1>;
          if (isLoading) return <h1>Loading ...</h1>;
          return data.map(
            (item: { title: { rendered: string }; id: number }) => {
              return (
                <span key={item.id} style={{ fontSize: "25px" }}>
                  {item.title.rendered}
                </span>
              );
            }
          );
        })()}
      </main>
    </>
  );
}
