import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import useSWR from "swr";

const inter = Inter({ subsets: ["latin"] });

const fetcher = (args: any) => fetch(args).then((res) => res.json());

export default function Home() {
  const { data, error, isLoading } = useSWR(
    "http://10.40.14.23/wp-json/wp/v2/headings",
    fetcher
  );

  if (error) return <span>failed to load</span>;
  if (isLoading) return <span>Loading ...</span>;

  const heading = data[0].acm_fields.heading;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>{heading}</h1>
      </main>
    </>
  );
}
